title: climbcode by climbcon
description: >-
  who needs a social life when you can obsess over algorithms and belay devices?
  join me as i share my world of programming, rock climbing, and mountain biking.
  expect rants, questionable climbing tips, and the occasional outdoor mishap.
  <br/>
  <br/>
  send questions and comments to my email below, thanks for reading! 

author: connor kuhn
email: connorisoutside@gmail.com

baseurl: ""
url: "ckuhn.github.io"

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

permalink: /:slug.html

theme_config:
  appearance: "auto"
  back_home_text: "../"
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed
